### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hslatman** [MSAdministrator/PhishReporter-Outlook-Add-In#4]
Any update on what license you would like this project to be filed under? On your blog your wrote you would update this repo and were leaning to GPL3.

I'm asking because I sort of 'forked' your code (actually, I copied the zip you provided a day before you put this repo online) and would like to include one. My repo can be found at https://github.com/hslatman/outlook-fraudehelpdesk-reporter. If you want, I can provide you with more details about its intended usage.

**Comment by MSAdministrator** [comment]
I've finally got around to updating the license.  It should be reflected on this project.  I am curious though of what your intended usage is and any ideas of making it more robust would entail?

Of course, if you don't mind sharing.

Thanks,

**Comment by hslatman** [comment]
Cool, I will soon update my project with the same license, and will make sure there will be credits pointing to you, as it's not a real fork of this project and the link between them is not completely obvious.

The add-on is likely going to be used by a Dutch organization, called Fraudehelpdesk (FHD). As part of their business they receive suspicious emails, after which they analyze the contents, in a somewhat, but increasingly, automated manner. I mention *likely*, because we first have to analyze whether the actual reporters of email are already using Outlook as their primary client. 

A for improvements: I dumped some ideas on my repo's roadmap. I think for the FHD customization options are less of an issue right now. What they'd like to see is the button showing up in at least one other location, namely the popup window you get when double clicking an email. The reference to the de-installation process is due to the fact that uninstalling the add-on via Programs and Features leaves some (or all) add-on files intact, resulting in the add-on not being removed from Outlook. This still has to be done manually, at least during my test results with the installer.
