### ISSUE TITLE
Add Reporter button on the Message ribbon bar

### ISSUE THREAD

**Issue by MSAdministrator** [MSAdministrator/PhishReporter-Outlook-Add-In#7]

**Comment by hslatman** [comment]
When debugging inside Outlook I found that there's an XML UI update error on the message ribbon bar. So far I haven't found a solution yet, but it has to do with the fact that the a certain control ID can't be found and has to do with TabMail. I think it has something to do with the fact that the message ribbon bar does not have that control identifier.

**Comment by MSAdministrator** [comment]
hslatman.  I had some free time so I have resolved this.  The Add-In should now be displayed on the ribbon bar when a message is opened.  Let me know if you have any issues!

**Comment by hslatman** [comment]
@MSAdministrator: I backported your changes to my project. Works like a charm so far! Thanks!
